version: '3.7'

services:
  web-bootcamp:
    container_name: apache_php
    image: web-bootcamp
    build:
      context: ./
    volumes:
      - /home/epuce/Public/web-bootcamp/local-env-setup/src:/var/www/html/
    ports:
      - 8000:80

  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=web-bootcamp-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
    ports:
      - "8082:3306"

  app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - mysql
    ports:
      - 8083:80
    volumes:
      - /sessions